"""
🟢 GREEN ZONE — Oracle STAFF schema + seed data.

Ratified decisions: docs/decision-log/AC-12-seed-staff.md.

This script is the **schema authority** for the demo per
[ADR-010](../../docs/adr/ADR-010-no-migration-tool.md). Run it whenever
the schema or seed data needs to be refreshed.

Usage (from `backend/`):

    .venv/bin/python -m scripts.seed_oracle
    # or
    .venv/bin/python scripts/seed_oracle.py

Reads `ORACLE_*` env vars via `app.core.config.get_settings()` — same
config the FastAPI app uses, so there's no parallel env-loading path.

All data is synthetic per ADR-007 + NFR-08. The 10 STAFF records mirror
DATA_MODEL.md §8 exactly. Email addresses use `@test.com` to leave no
ambiguity about the synthetic-ness.
"""
from __future__ import annotations

import sys
from typing import Iterable

import oracledb

# Allow `python scripts/seed_oracle.py` from `backend/` without a `-m`.
if __package__ is None or __package__ == "":
    import pathlib

    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from app.core.config import get_settings  # noqa: E402


# ---------------------------------------------------------------------------
# Schema — exact match to DATA_MODEL.md §4.1
# ---------------------------------------------------------------------------

_DROP_TABLE_STAFF = "DROP TABLE STAFF"

_CREATE_TABLE_STAFF = """\
CREATE TABLE STAFF (
    STAFF_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID         VARCHAR2(20)  NOT NULL UNIQUE,
    FULL_NAME           VARCHAR2(255) NOT NULL,
    EMAIL               VARCHAR2(255) NOT NULL UNIQUE,
    DEPARTMENT          VARCHAR2(100) NOT NULL,
    JOB_TITLE           VARCHAR2(100) NOT NULL,
    PROCUREMENT_LEVEL   NUMBER(1)     NOT NULL CHECK (PROCUREMENT_LEVEL BETWEEN 0 AND 3),
    ROLE                VARCHAR2(10)  NOT NULL CHECK (ROLE IN ('ADMIN', 'STAFF')),
    IDME_VERIFIED       CHAR(1)       NOT NULL CHECK (IDME_VERIFIED IN ('Y', 'N')),
    ACTIVE              CHAR(1)       NOT NULL CHECK (ACTIVE IN ('Y', 'N')),
    CREATED_DATE        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP,
    UPDATED_DATE        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP
)
"""

_INSERT_STAFF = """\
INSERT INTO STAFF (
    EMPLOYEE_ID, FULL_NAME, EMAIL, DEPARTMENT, JOB_TITLE,
    PROCUREMENT_LEVEL, ROLE, IDME_VERIFIED, ACTIVE
) VALUES (
    :employee_id, :full_name, :email, :department, :job_title,
    :procurement_level, :role, :idme_verified, :active
)
"""

# ORA-00942 = "table or view does not exist". First-run friendly.
_ORA_TABLE_DOES_NOT_EXIST = 942


# ---------------------------------------------------------------------------
# Seed data — DATA_MODEL.md §8 (10 records, all synthetic)
# ---------------------------------------------------------------------------


def _email_for(full_name: str) -> str:
    """Produce a synthetic `firstname.lastname@test.com`. Strips diacritics
    only loosely (DATA_MODEL §8 names are plain-ASCII anyway, so we don't
    pull in unicodedata for the demo).
    """
    parts = full_name.lower().split()
    # `Al-Hassan` becomes `al-hassan` — keep the hyphen so emails are
    # deterministic and unique.
    return f"{parts[0]}.{parts[-1]}@test.com"


_STAFF_SEED: list[dict[str, object]] = [
    {
        "employee_id": "FCPS-001",
        "full_name": "Sarah Mitchell",
        "department": "Administration",
        "job_title": "Procurement Coordinator",
        "procurement_level": 3,
        "role": "ADMIN",
    },
    {
        "employee_id": "FCPS-002",
        "full_name": "James Okafor",
        "department": "Administration",
        "job_title": "Procurement Coordinator",
        "procurement_level": 3,
        "role": "ADMIN",
    },
    {
        "employee_id": "FCPS-003",
        "full_name": "Linda Nguyen",
        "department": "Mathematics",
        "job_title": "Teacher",
        "procurement_level": 1,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-004",
        "full_name": "Marcus Thompson",
        "department": "Science",
        "job_title": "Teacher",
        "procurement_level": 1,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-005",
        "full_name": "Priya Patel",
        "department": "English",
        "job_title": "Teacher",
        "procurement_level": 1,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-006",
        "full_name": "David Hernandez",
        "department": "IT",
        "job_title": "Systems Administrator",
        "procurement_level": 2,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-007",
        "full_name": "Amara Johnson",
        "department": "Facilities",
        "job_title": "Facilities Manager",
        "procurement_level": 2,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-008",
        "full_name": "Robert Kim",
        "department": "Arts",
        "job_title": "Teacher",
        "procurement_level": 1,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-009",
        "full_name": "Fatima Al-Hassan",
        "department": "Special Ed",
        "job_title": "Teacher",
        "procurement_level": 1,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-010",
        "full_name": "Christopher Evans",
        "department": "PE",
        "job_title": "Teacher",
        "procurement_level": 0,
        "role": "STAFF",
    },
]


def _bind_rows() -> list[dict[str, object]]:
    """Decorate the seed list with `email`, `idme_verified`, `active`."""
    return [
        {
            **row,
            "email": _email_for(row["full_name"]),  # type: ignore[arg-type]
            "idme_verified": "Y",
            "active": "Y",
        }
        for row in _STAFF_SEED
    ]


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------


def _drop_table_staff(cursor: oracledb.Cursor) -> None:
    """`DROP TABLE STAFF`, swallowing ORA-00942 (table not found) so the
    script is first-run-friendly.
    """
    try:
        cursor.execute(_DROP_TABLE_STAFF)
        print("✓ Dropped STAFF")
    except oracledb.DatabaseError as exc:
        (err,) = exc.args
        if getattr(err, "code", None) == _ORA_TABLE_DOES_NOT_EXIST:
            print("· STAFF did not exist — skipping drop")
            return
        raise


def _create_table_staff(cursor: oracledb.Cursor) -> None:
    cursor.execute(_CREATE_TABLE_STAFF)
    print("✓ Created STAFF")


def _insert_staff_rows(cursor: oracledb.Cursor, rows: Iterable[dict[str, object]]) -> int:
    """Insert all rows; return the count actually inserted."""
    count = 0
    for row in rows:
        cursor.execute(_INSERT_STAFF, row)
        count += 1
    return count


def seed(connection: oracledb.Connection) -> None:
    """Run the full DROP → CREATE → INSERT lifecycle on the given connection.

    Exposed as a function so tests can drive it with a mocked connection.
    The CLI entrypoint (`main`) wraps this with connection setup and
    error → exit-code mapping.
    """
    with connection.cursor() as cursor:
        _drop_table_staff(cursor)
        _create_table_staff(cursor)
        rows = _bind_rows()
        n = _insert_staff_rows(cursor, rows)
        connection.commit()
        print(f"✓ Inserted {n} STAFF rows")


def main() -> int:
    settings = get_settings()
    dsn = oracledb.makedsn(
        host=settings.oracle_host,
        port=settings.oracle_port,
        service_name=settings.oracle_service_name,
    )
    try:
        conn = oracledb.connect(
            user=settings.oracle_user,
            password=settings.oracle_password,
            dsn=dsn,
        )
    except oracledb.DatabaseError as exc:
        print(f"✗ Could not connect to Oracle: {type(exc).__name__}", file=sys.stderr)
        return 1

    try:
        seed(conn)
    except oracledb.DatabaseError as exc:
        print(f"✗ Seed failed: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1
    finally:
        conn.close()

    return 0


if __name__ == "__main__":  # pragma: no cover — exercised in main()
    sys.exit(main())
