"""
🟢 GREEN ZONE — Oracle STAFF schema + seed data.

Ratified decisions: docs/decision-log/AC-12-seed-staff.md.

This script is the **schema authority** for the demo per
[ADR-010](../../docs/adr/ADR-010-no-migration-tool.md). Run it whenever
the schema or seed data needs to be refreshed.

Usage (from `backend/`):

    .venv/bin/python -m scripts.seed_oracle
    # or
    .venv/bin/python scripts/seed_oracle.py

Reads `ORACLE_*` env vars via `app.core.config.get_settings()` — same
config the FastAPI app uses, so there's no parallel env-loading path.

All data is synthetic per ADR-007 + NFR-08. The 10 STAFF records mirror
DATA_MODEL.md §8 exactly. Email addresses use `@test.com` to leave no
ambiguity about the synthetic-ness.
"""
from __future__ import annotations

import sys
from typing import Iterable

import oracledb

# Allow `python scripts/seed_oracle.py` from `backend/` without a `-m`.
if __package__ is None or __package__ == "":
    import pathlib

    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from app.core.config import get_settings  # noqa: E402


# ---------------------------------------------------------------------------
# Schema — exact match to DATA_MODEL.md §4.1
# ---------------------------------------------------------------------------

_DROP_TABLE_STAFF = "DROP TABLE STAFF"

_CREATE_TABLE_STAFF = """\
CREATE TABLE STAFF (
    STAFF_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID         VARCHAR2(20)  NOT NULL UNIQUE,
    FULL_NAME           VARCHAR2(255) NOT NULL,
    EMAIL               VARCHAR2(255) NOT NULL UNIQUE,
    DEPARTMENT          VARCHAR2(100) NOT NULL,
    JOB_TITLE           VARCHAR2(100) NOT NULL,
    PROCUREMENT_LEVEL   NUMBER(1)     NOT NULL CHECK (PROCUREMENT_LEVEL BETWEEN 0 AND 3),
    ROLE                VARCHAR2(10)  NOT NULL CHECK (ROLE IN ('ADMIN', 'STAFF')),
    IDME_VERIFIED       CHAR(1)       NOT NULL CHECK (IDME_VERIFIED IN ('Y', 'N')),
    ACTIVE              CHAR(1)       NOT NULL CHECK (ACTIVE IN ('Y', 'N')),
    CREATED_DATE        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP,
    UPDATED_DATE        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP
)
"""

_INSERT_STAFF = """\
INSERT INTO STAFF (
    EMPLOYEE_ID, FULL_NAME, EMAIL, DEPARTMENT, JOB_TITLE,
    PROCUREMENT_LEVEL, ROLE, IDME_VERIFIED, ACTIVE
) VALUES (
    :employee_id, :full_name, :email, :department, :job_title,
    :procurement_level, :role, :idme_verified, :active
)
"""

# AC-19 — PROCUREMENT_ITEMS schema (DATA_MODEL.md §4.2 + ADR-006 APPROVED_AT).
# BANK_DETAILS deliberately omitted (ADR-012).
_DROP_TABLE_PROCUREMENT_ITEMS = "DROP TABLE PROCUREMENT_ITEMS"

_CREATE_TABLE_PROCUREMENT_ITEMS = """\
CREATE TABLE PROCUREMENT_ITEMS (
    ITEM_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ITEM_NAME       VARCHAR2(255) NOT NULL,
    VENDOR_NAME     VARCHAR2(255) NOT NULL,
    CATEGORY        VARCHAR2(100) NOT NULL,
    STATUS          VARCHAR2(20)  NOT NULL CHECK (STATUS IN ('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED')),
    UNIT_PRICE      NUMBER(10,2),
    CONTACT_NAME    VARCHAR2(255),
    CONTACT_EMAIL   VARCHAR2(255),
    APPROVED_AT     TIMESTAMP WITH TIME ZONE,
    CREATED_DATE    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP,
    UPDATED_DATE    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP
)
"""

_INSERT_PROCUREMENT_ITEM = """\
INSERT INTO PROCUREMENT_ITEMS (
    ITEM_NAME, VENDOR_NAME, CATEGORY, STATUS, UNIT_PRICE,
    CONTACT_NAME, CONTACT_EMAIL, APPROVED_AT
) VALUES (
    :item_name, :vendor_name, :category, :status, :unit_price,
    :contact_name, :contact_email, :approved_at
)
"""

# ORA-00942 = "table or view does not exist". First-run friendly.
_ORA_TABLE_DOES_NOT_EXIST = 942


# ---------------------------------------------------------------------------
# Seed data — DATA_MODEL.md §8 (10 records, all synthetic)
# ---------------------------------------------------------------------------


def _email_for(full_name: str) -> str:
    """Produce a synthetic `firstname.lastname@test.com`. Strips diacritics
    only loosely (DATA_MODEL §8 names are plain-ASCII anyway, so we don't
    pull in unicodedata for the demo).
    """
    parts = full_name.lower().split()
    # `Al-Hassan` becomes `al-hassan` — keep the hyphen so emails are
    # deterministic and unique.
    return f"{parts[0]}.{parts[-1]}@test.com"


_STAFF_SEED: list[dict[str, object]] = [
    {
        "employee_id": "FCPS-001",
        "full_name": "Sarah Mitchell",
        "department": "Administration",
        "job_title": "Procurement Coordinator",
        "procurement_level": 3,
        "role": "ADMIN",
    },
    {
        "employee_id": "FCPS-002",
        "full_name": "James Okafor",
        "department": "Administration",
        "job_title": "Procurement Coordinator",
        "procurement_level": 3,
        "role": "ADMIN",
    },
    {
        "employee_id": "FCPS-003",
        "full_name": "Linda Nguyen",
        "department": "Mathematics",
        "job_title": "Teacher",
        "procurement_level": 1,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-004",
        "full_name": "Marcus Thompson",
        "department": "Science",
        "job_title": "Teacher",
        "procurement_level": 1,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-005",
        "full_name": "Priya Patel",
        "department": "English",
        "job_title": "Teacher",
        "procurement_level": 1,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-006",
        "full_name": "David Hernandez",
        "department": "IT",
        "job_title": "Systems Administrator",
        "procurement_level": 2,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-007",
        "full_name": "Amara Johnson",
        "department": "Facilities",
        "job_title": "Facilities Manager",
        "procurement_level": 2,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-008",
        "full_name": "Robert Kim",
        "department": "Arts",
        "job_title": "Teacher",
        "procurement_level": 1,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-009",
        "full_name": "Fatima Al-Hassan",
        "department": "Special Ed",
        "job_title": "Teacher",
        "procurement_level": 1,
        "role": "STAFF",
    },
    {
        "employee_id": "FCPS-010",
        "full_name": "Christopher Evans",
        "department": "PE",
        "job_title": "Teacher",
        "procurement_level": 0,
        "role": "STAFF",
    },
]


def _bind_rows() -> list[dict[str, object]]:
    """Decorate the seed list with `email`, `idme_verified`, `active`."""
    return [
        {
            **row,
            "email": _email_for(row["full_name"]),  # type: ignore[arg-type]
            "idme_verified": "Y",
            "active": "Y",
        }
        for row in _STAFF_SEED
    ]


# ---------------------------------------------------------------------------
# AC-19 — PROCUREMENT_ITEMS seed (15 rows per DATA_MODEL.md §8)
# ---------------------------------------------------------------------------

from datetime import datetime, timezone  # noqa: E402  — keep PROCUREMENT seed self-contained


def _vendor_email(contact_name: str, vendor_name: str) -> str:
    """`firstname.lastname@vendor.test`. Distinct from staff `@test.com`
    so a reader can tell vendor PII apart from staff PII at a glance.
    """
    parts = contact_name.lower().split()
    return f"{parts[0]}.{parts[-1]}@vendor.test"


def _approved(year: int, month: int, day: int) -> datetime:
    """Helper for ADR-006 APPROVED_AT timestamps. UTC, midday for clarity."""
    return datetime(year, month, day, 12, 0, 0, tzinfo=timezone.utc)


# 15 rows: 5 APPROVED, 4 PENDING, 3 UNDER_REVIEW, 3 REJECTED.
# Categories: Technology / Facilities / Supplies / Services / Furniture.
# APPROVED_AT is non-null only for APPROVED rows (AC19-D4).
_PROCUREMENT_SEED: list[dict[str, object]] = [
    # --- 5 APPROVED -----------------------------------------------------
    dict(
        item_name="Classroom laptops (15-pack)",
        vendor_name="Northstar Computing",
        category="Technology",
        status="APPROVED",
        unit_price=8499.00,
        contact_name="Alice Reyes",
        approved_at=_approved(2026, 1, 12),
    ),
    dict(
        item_name="HVAC quarterly service",
        vendor_name="MetroAir Facilities",
        category="Facilities",
        status="APPROVED",
        unit_price=2250.00,
        contact_name="Benjamin Park",
        approved_at=_approved(2026, 1, 22),
    ),
    dict(
        item_name="A4 copier paper, 50 cases",
        vendor_name="Statewide Office Supply",
        category="Supplies",
        status="APPROVED",
        unit_price=1199.50,
        contact_name="Cora Williams",
        approved_at=_approved(2026, 2, 3),
    ),
    dict(
        item_name="On-site IT support contract",
        vendor_name="BlueRidge IT Services",
        category="Services",
        status="APPROVED",
        unit_price=14500.00,
        contact_name="Devon Chen",
        approved_at=_approved(2026, 2, 14),
    ),
    dict(
        item_name="Library reading tables (8)",
        vendor_name="Heritage Furniture Co.",
        category="Furniture",
        status="APPROVED",
        unit_price=4200.00,
        contact_name="Elena Rossi",
        approved_at=_approved(2026, 3, 4),
    ),
    # --- 4 PENDING ------------------------------------------------------
    dict(
        item_name="Interactive whiteboards (5)",
        vendor_name="Northstar Computing",
        category="Technology",
        status="PENDING",
        unit_price=3199.00,
        contact_name="Alice Reyes",
        approved_at=None,
    ),
    dict(
        item_name="Cafeteria fridge replacement",
        vendor_name="MetroAir Facilities",
        category="Facilities",
        status="PENDING",
        unit_price=5475.00,
        contact_name="Benjamin Park",
        approved_at=None,
    ),
    dict(
        item_name="Cleaning supplies, annual",
        vendor_name="Statewide Office Supply",
        category="Supplies",
        status="PENDING",
        unit_price=8200.00,
        contact_name="Cora Williams",
        approved_at=None,
    ),
    dict(
        item_name="Network security audit",
        vendor_name="BlueRidge IT Services",
        category="Services",
        status="PENDING",
        unit_price=6800.00,
        contact_name="Devon Chen",
        approved_at=None,
    ),
    # --- 3 UNDER_REVIEW -------------------------------------------------
    dict(
        item_name="Science-lab stools (40)",
        vendor_name="Heritage Furniture Co.",
        category="Furniture",
        status="UNDER_REVIEW",
        unit_price=2200.00,
        contact_name="Elena Rossi",
        approved_at=None,
    ),
    dict(
        item_name="Cafeteria food-service supplies",
        vendor_name="GreenLeaf Food Distributors",
        category="Supplies",
        status="UNDER_REVIEW",
        unit_price=12300.00,
        contact_name="Farhan Ahmed",
        approved_at=None,
    ),
    dict(
        item_name="District-wide tablet refresh",
        vendor_name="Northstar Computing",
        category="Technology",
        status="UNDER_REVIEW",
        unit_price=42600.00,
        contact_name="Alice Reyes",
        approved_at=None,
    ),
    # --- 3 REJECTED -----------------------------------------------------
    dict(
        item_name="Outdated software licences",
        vendor_name="Legacy Systems LLC",
        category="Technology",
        status="REJECTED",
        unit_price=995.00,
        contact_name="Grace Tan",
        approved_at=None,
    ),
    dict(
        item_name="Parking-lot resealing (unverified vendor)",
        vendor_name="QuickFix Asphalt",
        category="Facilities",
        status="REJECTED",
        unit_price=7800.00,
        contact_name="Hugo Martinez",
        approved_at=None,
    ),
    dict(
        item_name="Bulk binder order (overcosted)",
        vendor_name="Statewide Office Supply",
        category="Supplies",
        status="REJECTED",
        unit_price=4500.00,
        contact_name="Cora Williams",
        approved_at=None,
    ),
]


def _procurement_bind_rows() -> list[dict[str, object]]:
    return [
        {
            **row,
            "contact_email": _vendor_email(
                row["contact_name"], row["vendor_name"]  # type: ignore[arg-type]
            ),
        }
        for row in _PROCUREMENT_SEED
    ]


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------


def _drop_table(cursor: oracledb.Cursor, drop_sql: str, name: str) -> None:
    """Run a `DROP TABLE` statement, swallowing ORA-00942 (table not found)
    so the script is first-run-friendly. Shared by both STAFF and
    PROCUREMENT_ITEMS (AC-19).
    """
    try:
        cursor.execute(drop_sql)
        print(f"✓ Dropped {name}")
    except oracledb.DatabaseError as exc:
        (err,) = exc.args
        if getattr(err, "code", None) == _ORA_TABLE_DOES_NOT_EXIST:
            print(f"· {name} did not exist — skipping drop")
            return
        raise


def _insert_rows(
    cursor: oracledb.Cursor,
    insert_sql: str,
    rows: Iterable[dict[str, object]],
) -> int:
    """Insert all rows via one parameter-bound statement; return the count."""
    count = 0
    for row in rows:
        cursor.execute(insert_sql, row)
        count += 1
    return count


def seed(connection: oracledb.Connection) -> None:
    """Run the full DROP → CREATE → INSERT lifecycle for every demo table.

    AC-12: STAFF (10 rows).
    AC-19: PROCUREMENT_ITEMS (15 rows) — schema includes APPROVED_AT
    (ADR-006), excludes BANK_DETAILS (ADR-012). No AUDIT_LOG (ADR-012).

    Exposed as a function so tests can drive it with a mocked connection.
    The CLI entrypoint (`main`) wraps this with connection setup and
    error → exit-code mapping.
    """
    with connection.cursor() as cursor:
        # --- STAFF ---
        _drop_table(cursor, _DROP_TABLE_STAFF, "STAFF")
        cursor.execute(_CREATE_TABLE_STAFF)
        print("✓ Created STAFF")
        staff_count = _insert_rows(cursor, _INSERT_STAFF, _bind_rows())
        print(f"✓ Inserted {staff_count} STAFF rows")

        # --- PROCUREMENT_ITEMS (AC-19) ---
        _drop_table(
            cursor, _DROP_TABLE_PROCUREMENT_ITEMS, "PROCUREMENT_ITEMS"
        )
        cursor.execute(_CREATE_TABLE_PROCUREMENT_ITEMS)
        print("✓ Created PROCUREMENT_ITEMS")
        proc_count = _insert_rows(
            cursor, _INSERT_PROCUREMENT_ITEM, _procurement_bind_rows()
        )
        print(f"✓ Inserted {proc_count} PROCUREMENT_ITEMS rows")

        connection.commit()


def main() -> int:
    settings = get_settings()
    dsn = oracledb.makedsn(
        host=settings.oracle_host,
        port=settings.oracle_port,
        service_name=settings.oracle_service_name,
    )
    try:
        conn = oracledb.connect(
            user=settings.oracle_user,
            password=settings.oracle_password,
            dsn=dsn,
        )
    except oracledb.DatabaseError as exc:
        print(f"✗ Could not connect to Oracle: {type(exc).__name__}", file=sys.stderr)
        return 1

    try:
        seed(conn)
    except oracledb.DatabaseError as exc:
        print(f"✗ Seed failed: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1
    finally:
        conn.close()

    return 0


if __name__ == "__main__":  # pragma: no cover — exercised in main()
    sys.exit(main())
