"""Tests for `scripts.seed_oracle` — AC-12.

Maps to ratified decisions in `docs/decision-log/AC-12-seed-staff.md`:

* AC12-D2 — idempotency: DROP first, ORA-00942 swallowed on first run.
* AC12-D3 — CREATE TABLE matches DATA_MODEL.md §4.1.
* AC12-D4 — parameter-bound INSERTs only.
* AC12-D6 — exactly 10 rows from DATA_MODEL.md §8 in order, emails @test.com.

Mocks `oracledb` at the boundary, same pattern as AC-11. No real Oracle.
"""
from __future__ import annotations

from unittest.mock import MagicMock

import oracledb
import pytest

from scripts.seed_oracle import (
    _CREATE_TABLE_STAFF,
    _DROP_TABLE_STAFF,
    _INSERT_STAFF,
    _STAFF_SEED,
    _bind_rows,
    _email_for,
    seed,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


def _make_connection(*, drop_raises=None) -> MagicMock:
    """Build a mock connection whose cursor is itself a MagicMock and a
    context manager. Tracks `execute` calls in order.

    When `drop_raises` is set, EVERY `DROP TABLE …` execute raises that
    error — simulates a true first-run state where neither STAFF nor
    PROCUREMENT_ITEMS exist yet.
    """
    cursor = MagicMock(name="cursor")
    if drop_raises is not None:
        def side_effect(sql, *args, **kwargs):
            if sql.startswith("DROP TABLE"):
                raise drop_raises
            return None

        cursor.execute.side_effect = side_effect

    cursor_ctx = MagicMock(name="cursor_ctx")
    cursor_ctx.__enter__.return_value = cursor
    cursor_ctx.__exit__.return_value = False

    connection = MagicMock(name="connection")
    connection.cursor.return_value = cursor_ctx
    connection._cursor = cursor
    return connection


def _ora_error(code: int) -> oracledb.DatabaseError:
    """Build a DatabaseError whose `.args[0].code == code`."""
    err = MagicMock()
    err.code = code
    return oracledb.DatabaseError(err)


# ---------------------------------------------------------------------------
# Seed data discipline
# ---------------------------------------------------------------------------


def test_seed_has_exactly_10_rows_matching_data_model_8():
    """Per ADR-015: the breakdown is now driven by ROLE only — 2 supervisors,
    7 regular staff, 1 non-staff (10 total).
    """
    assert len(_STAFF_SEED) == 10
    by_role = [r["role"] for r in _STAFF_SEED]
    assert by_role.count("PROCUREMENT_SUPERVISOR") == 2
    assert by_role.count("REGULAR_STAFF") == 7
    assert by_role.count("NON_STAFF") == 1
    # No row should carry the dropped PROCUREMENT_LEVEL field.
    for r in _STAFF_SEED:
        assert "procurement_level" not in r


def test_seed_employee_ids_are_EMP_001_to_010_in_order():
    expected = [f"EMP-{n:03d}" for n in range(1, 11)]
    assert [r["employee_id"] for r in _STAFF_SEED] == expected


def test_email_for_uses_test_dot_com_and_lowercase():
    assert _email_for("Sarah Mitchell") == "sarah.mitchell@test.com"
    assert _email_for("Fatima Al-Hassan") == "fatima.al-hassan@test.com"


def test_bound_rows_decorate_with_email_idme_verified_active():
    rows = _bind_rows()
    assert len(rows) == 10
    for row in rows:
        assert row["email"].endswith("@test.com")
        assert "spp" not in row["email"]
        assert row["idme_verified"] == "Y"
        assert row["active"] == "Y"


# ---------------------------------------------------------------------------
# Schema discipline (AC12-D3)
# ---------------------------------------------------------------------------


def test_create_table_sql_contains_all_required_columns_and_constraints():
    sql = _CREATE_TABLE_STAFF
    # Every column from DATA_MODEL.md §4.1 (post-ADR-015 — no PROCUREMENT_LEVEL).
    for col in [
        "STAFF_ID", "EMPLOYEE_ID", "FULL_NAME", "EMAIL", "DEPARTMENT",
        "JOB_TITLE", "ROLE", "IDME_VERIFIED", "ACTIVE",
        "CREATED_DATE", "UPDATED_DATE",
    ]:
        assert col in sql, f"missing column {col} in CREATE TABLE"
    # PROCUREMENT_LEVEL must NOT appear (ADR-015 removed it).
    assert "PROCUREMENT_LEVEL" not in sql

    # Critical constraints.
    assert "PRIMARY KEY" in sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "UNIQUE" in sql                          # employee_id + email
    assert (
        "CHECK (ROLE IN ('PROCUREMENT_SUPERVISOR', 'REGULAR_STAFF', 'NON_STAFF'))"
        in sql
    )
    assert "CHECK (IDME_VERIFIED IN ('Y', 'N'))" in sql
    assert "CHECK (ACTIVE IN ('Y', 'N'))" in sql


def test_insert_sql_uses_named_bind_variables_not_fstring():
    """AC12-D4 — INSERT must use named bind variables. Anything else is
    a SQL-injection footgun.
    """
    sql = _INSERT_STAFF
    assert "{" not in sql
    assert "%s" not in sql
    for col in ["employee_id", "full_name", "email", "role"]:
        assert f":{col}" in sql


# ---------------------------------------------------------------------------
# Runner — DROP → CREATE → 10 INSERTs (AC12-D2, AC12-D8)
# ---------------------------------------------------------------------------


def test_seed_runs_drop_create_then_10_inserts():
    conn = _make_connection()
    seed(conn)

    executed_sqls = [call.args[0] for call in conn._cursor.execute.call_args_list]

    assert executed_sqls[0] == _DROP_TABLE_STAFF
    assert executed_sqls[1] == _CREATE_TABLE_STAFF
    inserts = [sql for sql in executed_sqls[2:] if sql == _INSERT_STAFF]
    assert len(inserts) == 10
    conn.commit.assert_called_once()


def test_seed_inserts_pass_the_bound_row_dicts():
    """AC12-D4 — each INSERT call's second positional arg is the bind dict
    for that row. Spot-check the first and last rows.
    """
    conn = _make_connection()
    seed(conn)

    insert_calls = [
        call
        for call in conn._cursor.execute.call_args_list
        if call.args[0] == _INSERT_STAFF
    ]
    first = insert_calls[0].args[1]
    last = insert_calls[-1].args[1]

    assert first["employee_id"] == "EMP-001"
    assert first["full_name"] == "Sarah Mitchell"
    assert first["email"] == "sarah.mitchell@test.com"
    assert first["role"] == "PROCUREMENT_SUPERVISOR"

    assert last["employee_id"] == "EMP-010"
    assert last["role"] == "NON_STAFF"


def test_seed_swallows_ora_00942_on_first_run():
    """AC12-D2 — if STAFF doesn't exist yet, DROP raises ORA-00942 and the
    script continues to CREATE + INSERT without error.
    """
    conn = _make_connection(drop_raises=_ora_error(942))

    seed(conn)  # must not raise

    executed_sqls = [call.args[0] for call in conn._cursor.execute.call_args_list]
    # CREATE still runs (after the swallowed DROP error).
    assert _CREATE_TABLE_STAFF in executed_sqls
    inserts = [sql for sql in executed_sqls if sql == _INSERT_STAFF]
    assert len(inserts) == 10


def test_seed_propagates_other_oracle_errors():
    """AC12-D2 — ORA-00942 is the only error we swallow on DROP. Any other
    code (e.g. insufficient privileges) must propagate.
    """
    conn = _make_connection(drop_raises=_ora_error(1031))  # insufficient privileges

    with pytest.raises(oracledb.DatabaseError):
        seed(conn)


# ---------------------------------------------------------------------------
# Synthetic-PII guardrail (org policy + ADR-007)
# ---------------------------------------------------------------------------


def test_no_seed_row_uses_a_real_looking_spp_email():
    """Belt-and-braces — every seed email must use @test.com, never any
    spp.edu / spp.org / similar that could be mistaken for real data.
    """
    for row in _bind_rows():
        email = row["email"]
        assert email.endswith("@test.com"), f"non-test email: {email}"
        local = email.split("@")[0]
        # Local part must NOT contain the literal "spp" anywhere — extra
        # safety against accidental real-data shapes.
        assert "spp" not in local.lower(), f"spp in email local part: {email}"


# ===========================================================================
# AC-19 — PROCUREMENT_ITEMS seed
# ===========================================================================

from scripts.seed_oracle import (
    _CREATE_TABLE_PROCUREMENT_ITEMS,
    _DROP_TABLE_PROCUREMENT_ITEMS,
    _INSERT_PROCUREMENT_ITEM,
    _PROCUREMENT_SEED,
    _procurement_bind_rows,
)


def test_procurement_seed_has_exactly_15_rows():
    assert len(_PROCUREMENT_SEED) == 15


def test_procurement_seed_status_breakdown_matches_data_model_8():
    by_status = [r["status"] for r in _PROCUREMENT_SEED]
    assert by_status.count("APPROVED") == 5
    assert by_status.count("PENDING") == 4
    assert by_status.count("UNDER_REVIEW") == 3
    assert by_status.count("REJECTED") == 3


def test_approved_at_is_set_iff_status_is_approved():
    """AC19-D4 — APPROVED_AT non-null only for APPROVED rows."""
    for row in _PROCUREMENT_SEED:
        if row["status"] == "APPROVED":
            assert row["approved_at"] is not None, row
        else:
            assert row["approved_at"] is None, row


def test_procurement_create_table_includes_approved_at_excludes_bank_details():
    sql = _CREATE_TABLE_PROCUREMENT_ITEMS
    # ADR-006 lives:
    assert "APPROVED_AT" in sql
    # ADR-012 enforced:
    assert "BANK_DETAILS" not in sql
    # Required columns:
    for col in [
        "ITEM_ID", "ITEM_NAME", "VENDOR_NAME", "CATEGORY", "STATUS",
        "UNIT_PRICE", "CONTACT_NAME", "CONTACT_EMAIL", "CREATED_DATE",
        "UPDATED_DATE",
    ]:
        assert col in sql, f"missing column {col}"
    # CHECK constraint on STATUS.
    assert (
        "CHECK (STATUS IN ('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED'))"
        in sql
    )


def test_procurement_insert_uses_named_bind_variables():
    sql = _INSERT_PROCUREMENT_ITEM
    assert "{" not in sql
    assert "%s" not in sql
    for col in ["item_name", "vendor_name", "status", "approved_at"]:
        assert f":{col}" in sql


def test_procurement_emails_have_no_spp_substring():
    """AC19-D5 — vendor emails use @vendor.test, never anything looking
    like real Staff Procurement Portal data.
    """
    for row in _procurement_bind_rows():
        email = row["contact_email"]
        assert email.endswith("@vendor.test"), email
        assert "spp" not in email.lower(), email


def test_seed_runs_both_table_pipelines_in_order():
    """AC19-D7 — seed() drops/creates/inserts STAFF, then drops/creates/
    inserts PROCUREMENT_ITEMS, then commits once.
    """
    conn = _make_connection()
    seed(conn)

    executed_sqls = [call.args[0] for call in conn._cursor.execute.call_args_list]

    # Expected sequence of *distinct* SQL statements:
    seq = [
        s for s in executed_sqls
        if s in {
            _DROP_TABLE_STAFF,
            _CREATE_TABLE_STAFF,
            _DROP_TABLE_PROCUREMENT_ITEMS,
            _CREATE_TABLE_PROCUREMENT_ITEMS,
        }
    ]
    assert seq == [
        _DROP_TABLE_STAFF,
        _CREATE_TABLE_STAFF,
        _DROP_TABLE_PROCUREMENT_ITEMS,
        _CREATE_TABLE_PROCUREMENT_ITEMS,
    ]
    # 10 STAFF + 15 PROC inserts.
    assert executed_sqls.count(_INSERT_STAFF) == 10
    assert executed_sqls.count(_INSERT_PROCUREMENT_ITEM) == 15
    conn.commit.assert_called_once()
