"""Tests for `scripts.seed_oracle` — AC-12.

Maps to ratified decisions in `docs/decision-log/AC-12-seed-staff.md`:

* AC12-D2 — idempotency: DROP first, ORA-00942 swallowed on first run.
* AC12-D3 — CREATE TABLE matches DATA_MODEL.md §4.1.
* AC12-D4 — parameter-bound INSERTs only.
* AC12-D6 — exactly 10 rows from DATA_MODEL.md §8 in order, emails @test.com.

Mocks `oracledb` at the boundary, same pattern as AC-11. No real Oracle.
"""
from __future__ import annotations

from unittest.mock import MagicMock

import oracledb
import pytest

from scripts.seed_oracle import (
    _CREATE_TABLE_STAFF,
    _DROP_TABLE_STAFF,
    _INSERT_STAFF,
    _STAFF_SEED,
    _bind_rows,
    _email_for,
    seed,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


def _make_connection(*, drop_raises=None) -> MagicMock:
    """Build a mock connection whose cursor is itself a MagicMock and a
    context manager. Tracks `execute` calls in order.
    """
    cursor = MagicMock(name="cursor")
    if drop_raises is not None:
        # Only the DROP call raises; CREATE + INSERT succeed normally.
        def side_effect(sql, *args, **kwargs):
            if sql == _DROP_TABLE_STAFF:
                raise drop_raises
            return None

        cursor.execute.side_effect = side_effect

    cursor_ctx = MagicMock(name="cursor_ctx")
    cursor_ctx.__enter__.return_value = cursor
    cursor_ctx.__exit__.return_value = False

    connection = MagicMock(name="connection")
    connection.cursor.return_value = cursor_ctx
    connection._cursor = cursor
    return connection


def _ora_error(code: int) -> oracledb.DatabaseError:
    """Build a DatabaseError whose `.args[0].code == code`."""
    err = MagicMock()
    err.code = code
    return oracledb.DatabaseError(err)


# ---------------------------------------------------------------------------
# Seed data discipline
# ---------------------------------------------------------------------------


def test_seed_has_exactly_10_rows_matching_data_model_8():
    assert len(_STAFF_SEED) == 10
    # Spot-check the headcount per level / role — matches DATA_MODEL.md §8.
    by_role = [r["role"] for r in _STAFF_SEED]
    by_level = [r["procurement_level"] for r in _STAFF_SEED]
    assert by_role.count("ADMIN") == 2
    assert by_role.count("STAFF") == 8
    assert by_level.count(3) == 2
    assert by_level.count(2) == 2
    assert by_level.count(1) == 5
    assert by_level.count(0) == 1


def test_seed_employee_ids_are_FCPS_001_to_010_in_order():
    expected = [f"FCPS-{n:03d}" for n in range(1, 11)]
    assert [r["employee_id"] for r in _STAFF_SEED] == expected


def test_email_for_uses_test_dot_com_and_lowercase():
    assert _email_for("Sarah Mitchell") == "sarah.mitchell@test.com"
    assert _email_for("Fatima Al-Hassan") == "fatima.al-hassan@test.com"


def test_bound_rows_decorate_with_email_idme_verified_active():
    rows = _bind_rows()
    assert len(rows) == 10
    for row in rows:
        assert row["email"].endswith("@test.com")
        assert "fcps" not in row["email"]
        assert row["idme_verified"] == "Y"
        assert row["active"] == "Y"


# ---------------------------------------------------------------------------
# Schema discipline (AC12-D3)
# ---------------------------------------------------------------------------


def test_create_table_sql_contains_all_required_columns_and_constraints():
    sql = _CREATE_TABLE_STAFF
    # Every column from DATA_MODEL.md §4.1.
    for col in [
        "STAFF_ID", "EMPLOYEE_ID", "FULL_NAME", "EMAIL", "DEPARTMENT",
        "JOB_TITLE", "PROCUREMENT_LEVEL", "ROLE", "IDME_VERIFIED", "ACTIVE",
        "CREATED_DATE", "UPDATED_DATE",
    ]:
        assert col in sql, f"missing column {col} in CREATE TABLE"

    # Critical constraints.
    assert "PRIMARY KEY" in sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "UNIQUE" in sql                          # employee_id + email
    assert "CHECK (ROLE IN ('ADMIN', 'STAFF'))" in sql
    assert "CHECK (IDME_VERIFIED IN ('Y', 'N'))" in sql
    assert "CHECK (ACTIVE IN ('Y', 'N'))" in sql
    assert "CHECK (PROCUREMENT_LEVEL BETWEEN 0 AND 3)" in sql


def test_insert_sql_uses_named_bind_variables_not_fstring():
    """AC12-D4 — INSERT must use named bind variables. Anything else is
    a SQL-injection footgun.
    """
    sql = _INSERT_STAFF
    assert "{" not in sql
    assert "%s" not in sql
    for col in ["employee_id", "full_name", "email", "role"]:
        assert f":{col}" in sql


# ---------------------------------------------------------------------------
# Runner — DROP → CREATE → 10 INSERTs (AC12-D2, AC12-D8)
# ---------------------------------------------------------------------------


def test_seed_runs_drop_create_then_10_inserts():
    conn = _make_connection()
    seed(conn)

    executed_sqls = [call.args[0] for call in conn._cursor.execute.call_args_list]

    assert executed_sqls[0] == _DROP_TABLE_STAFF
    assert executed_sqls[1] == _CREATE_TABLE_STAFF
    inserts = [sql for sql in executed_sqls[2:] if sql == _INSERT_STAFF]
    assert len(inserts) == 10
    conn.commit.assert_called_once()


def test_seed_inserts_pass_the_bound_row_dicts():
    """AC12-D4 — each INSERT call's second positional arg is the bind dict
    for that row. Spot-check the first and last rows.
    """
    conn = _make_connection()
    seed(conn)

    insert_calls = [
        call
        for call in conn._cursor.execute.call_args_list
        if call.args[0] == _INSERT_STAFF
    ]
    first = insert_calls[0].args[1]
    last = insert_calls[-1].args[1]

    assert first["employee_id"] == "FCPS-001"
    assert first["full_name"] == "Sarah Mitchell"
    assert first["email"] == "sarah.mitchell@test.com"
    assert first["role"] == "ADMIN"
    assert first["procurement_level"] == 3

    assert last["employee_id"] == "FCPS-010"
    assert last["procurement_level"] == 0


def test_seed_swallows_ora_00942_on_first_run():
    """AC12-D2 — if STAFF doesn't exist yet, DROP raises ORA-00942 and the
    script continues to CREATE + INSERT without error.
    """
    conn = _make_connection(drop_raises=_ora_error(942))

    seed(conn)  # must not raise

    executed_sqls = [call.args[0] for call in conn._cursor.execute.call_args_list]
    # CREATE still runs (after the swallowed DROP error).
    assert _CREATE_TABLE_STAFF in executed_sqls
    inserts = [sql for sql in executed_sqls if sql == _INSERT_STAFF]
    assert len(inserts) == 10


def test_seed_propagates_other_oracle_errors():
    """AC12-D2 — ORA-00942 is the only error we swallow on DROP. Any other
    code (e.g. insufficient privileges) must propagate.
    """
    conn = _make_connection(drop_raises=_ora_error(1031))  # insufficient privileges

    with pytest.raises(oracledb.DatabaseError):
        seed(conn)


# ---------------------------------------------------------------------------
# Synthetic-PII guardrail (org policy + ADR-007)
# ---------------------------------------------------------------------------


def test_no_seed_row_uses_a_real_looking_fcps_email():
    """Belt-and-braces — every seed email must use @test.com, never any
    fcps.edu / fcps.org / similar that could be mistaken for real data.
    """
    for row in _bind_rows():
        email = row["email"]
        assert email.endswith("@test.com"), f"non-test email: {email}"
        local = email.split("@")[0]
        # Local part must NOT contain the literal "fcps" anywhere — extra
        # safety against accidental real-data shapes.
        assert "fcps" not in local.lower(), f"fcps in email local part: {email}"
